### PR TITLE
Hit the API

### PR DESCRIPTION
**Pull request by Ashnaali3255**
-  I use the API to create a new game with my chosen name.
- Make sure that you saved the ID of your game that will be returned by API.
- I implement the "Refresh" button that will get all scores for a game created by me from the API (receiving data from the API and parsing the JSON).
- I implement the form "Submit" button that will save a score for a game created by you (sending data to the API).
- I use arrow functions instead of the function keyword.
- I use async and await JavaScript features to consume the API.

### CODE REVIEW

**Review by IngDavidTM — CHANGES_REQUESTED** [review]
## Hi @Ashnaali3255 🙋‍♂️, 

Good job so far!
You have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!



## Top highlight 🎯
- The Pull Request follows the GitFlow ✅ 
- The PR title and description are professional and descriptive ✅ 
- Linters are working properly ✅ 

## Suggested changes

- [ ] You have done an excellent job in implementing the functions to call the API :+1:. However, there seem to be some errors when users attempt to both POST and GET elements from the API. It would be best to investigate and determine the cause of these errors. One possibility is that there may be some issues with the syntax or logic of the API calls (make sure that you are using the game code). This can include incorrect URL endpoints or parameters, incorrect use of HTTP methods, or errors in the format of the data being sent or received.


https://user-images.githubusercontent.com/105117832/224022802-37e9f3de-fc2c-4901-9d43-51dcbe8f0c09.mp4



- [x] _Check the comments under the review._ ⬇

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Ashnaali3255** [comment]
@IngDavidTM Hi! Can you help me please I tried a lot but all in vain... If you will help me I will be thankful to you.

**Comment by IngDavidTM** [comment]
> @IngDavidTM Hi! Can you help me please I tried a lot but all in vain... If you will help me I will be thankful to you.

Hi @Ashnaali3255, I noticed that you are not adding the code that the first game sent to you in the URL. For example instead of using this `https://us-central1-js-capstone-backend.cloudfunctions.net/api/games/` you should use `https://us-central1-js-capstone-backend.cloudfunctions.net/api/games/4tfml0QLmgKTloHBYIf5/scores/'`
[Here ](https://github.com/IngDavidTM/leaderboard/pull/2/files#diff-3ac4c10607bc5ea19cf532f75dc6163b93f6bc6dbae03f837ec89bca416d98ec) you can find an example of what I did in my Leaderboard

**Comment by Ashnaali3255** [comment]
@IngDavidTM  where i get this link from "4tfml0QLmgKTloHBYIf5/scores/"???

**Comment by IngDavidTM** [comment]
> @IngDavidTM where i get this link from "4tfml0QLmgKTloHBYIf5/scores/"???

You should generate it only once using the information from the API
Screenshot from 2023-03-09 08-07-05
In the example that I sent to you, I did it in `setNewGame.js`

**Comment by Ashnaali3255** [comment]
@IngDavidTM Thank you so much. It really means a lot.

**Review by leonardodiasb — APPROVED** [review]
# Status: ✔️ Project Approved ✔️ 

Hello @Ashnaali3255 🔥 

You worked hard in all the instructions that the previous Code Reviewers give you👍🏽 

Now you can merge this branch 🚀 

## Highlights

The Pull Request follows the GitFlow ✅
The PR title and description are professional and descriptive ✅
Linters are working properly ✅
API calls working fine ✅ 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
